### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by izengpan** [LRMPUT/PlaneSLAM#1]
Hello, thanks for your share.
When I run the codes, and errors was occured when I use "**make**" the whole PlaneSLAM.
And the errors are the same type:

CMakeFiles/PlaneSLAM.dir/src/main.cpp.o：in function ‘main’：
/home/zp/download/PlaneSLAM-master/src/main.cpp:151：  undefined reference to ‘g2o::internal::fromVectorQT(Eigen::Matrix<double, 7, 1, 0, 7, 1> const&)’
/home/zp/download/PlaneSLAM-master/src/main.cpp:152：  undefined reference to ‘g2o::internal::fromVectorQT(Eigen::Matrix<double, 7, 1, 0, 7, 1> const&)’
/home/zp/download/PlaneSLAM-master/src/main.cpp:154： undefined reference to ‘g2o::internal::toVectorQT(Eigen::Transform<double, 3, 1, 0> const&)’
/home/zp/download/PlaneSLAM-master/src/main.cpp:170： undefined reference to ‘g2o::internal::fromVectorQT(Eigen::Matrix<double, 7, 1, 0, 7, 1> const&)’
/home/zp/download/PlaneSLAM-master/src/main.cpp:171： undefined reference to‘g2o::internal::fromVectorQT(Eigen::Matrix<double, 7, 1, 0, 7, 1> const&)’
/home/zp/download/PlaneSLAM-master/src/main.cpp:174： undefined reference to ‘g2o::internal::toVectorQT(Eigen::Transform<double, 3, 1, 0> const&)’
/home/zp/download/PlaneSLAM-master/src/main.cpp:262： undefined reference to ‘g2o::internal::toVectorQT(Eigen::Transform<double, 3, 1, 0> const&)’
/home/zp/download/PlaneSLAM-master/src/main.cpp:271： undefined reference to ‘g2o::SparseOptimizer::SparseOptimizer()’

CMakeFiles/PlaneSLAM.dir/src/main.cpp.o：in function ‘g2o::G2OBatchStatistics::globalStats()’：
/home/zp/download/PlaneSLAM-master/3rdParty/g2o/g2o/core/batch_stats.h:73： undefined reference to ‘g2o::G2OBatchStatistics::_globalStats’
CMakeFiles/PlaneSLAM.dir/src/main.cpp.o：in function g2o::BlockSolverBase::~BlockSolverBase()’：
/home/zp/download/PlaneSLAM-master/3rdParty/g2o/g2o/core/block_solver.h:85： undefined reference to ‘g2o::Solver::~Solver()’

**undefined reference.**
Have you ever confronted this problem?

**Comment by jwietrzykowski** [comment]
Hi,

clearly it is a linker error regarding g2o. Do you have any other version of g2o installed in your system (other than the one in 3rdParty directory)?

**Comment by izengpan** [comment]
Thanks for your kind reply.
Yes, I have all ready installed one in my system.
And I run the codes in ubuntu 16.04.
Do you mean that I should use another g2o folder to replace the one in the 3rdParty?
And I have tried, there are mistakes in the process of making the g2o.
It said that my g2o doesn't have some .h and .cpp files, and I added them from your g2o, but more mistakes ocuured. 
emmm, I don't know how to handle this problem.

**Comment by jwietrzykowski** [comment]
Try uninstalling any other versions of g2o library from your system and installing only the one from 3rdParty directory. The code is not compatible with newer versions of g2o and included g2o has additional code for handing planes.
